### ISSUE TITLE
你是否有意向尝试二次元？

### ISSUE THREAD

**Issue by egoist** [djyde/ama#3]
越来越多的程序同时也是死宅（喜欢看动漫），

你是否有抵抗这种同化的倾向，让你做出这种坚持的理由是什么？

以及如果你抵抗这种趋势，那你是怎么看待这群程序员兼二次元爱好者的？

（最后，我 SOX 教赛高！）

**Comment by djyde** [comment]
我对二次元没有感觉 :hand:
